name=Raster_Bot
version=0.0.1
author=Bob Hammell
maintainer=Bob Hammell
sentence=Firmware for the Raster Bot project.
paragraph=Arduino library for controlling Raster Bot hardware.
category=Device Control
url=https://github.com/rhammell/raster-bot
architectures=esp32
depends=Adafruit GFX Library, Adafruit ILI9341, Adafruit FT6206 Library
